language: python
install:
    - pip install jalaali
python:
    - "2.6"
    - "2.7"
    - "3.4"
    - "3.5"
script:
    - coverage run --source=jalaali setup.py test
after_success:
    - bash <(curl -s https://codecov.io/bash)
notifications:
  email: false

